// <auto-generated />
using DateME.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DateME.Migrations
{
    [DbContext(typeof(DateApplicationContext))]
    [Migration("20220126215220_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("DateME.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            Category = "Comdedy",
                            Director = "The Farrelly Brothers",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Dumb & Dumber",
                            Year = 1994
                        },
                        new
                        {
                            ApplicationId = 2,
                            Category = "Comdedy",
                            Director = "John Hughes",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Ferris Bueller’s Day Off",
                            Year = 1986
                        },
                        new
                        {
                            ApplicationId = 3,
                            Category = "Comdedy",
                            Director = "Michael Ritchie",
                            Edited = false,
                            Rating = "PG",
                            Title = "Fletch",
                            Year = 1985
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
